services:
  matchmaking:
    image: matchmaking:latest
    hostname: matchmaking
    build: 
      dockerfile: dockerfile
    expose:
      - "8080"
    environment:
      - ENVIRONMENT=development
    volumes:
      - './config:/config'
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - matchmaking
    ports:
      - "4000:4000"
networks:
  default:
    driver: bridge
    name: matchmaking
